[package]
name = "mcircuit"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.126", features = ["derive"]}
bincode = "1.3.3"
variant_count = "1.1"
rand = "0.8.4"
